### ISSUE TITLE
Replace accordions with sub lists

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards-docs#101]
This idea proposal was submitting to us via email by Isabelle Giuong. Here is what she wrote:

> On the same site, remove accordions and have all of the stuff that'd be in there in the "usa-sidenav-sub_list" class instead. Right now, there's a mix and it's confusing and hard to navigate if you're at the middle/bottom of a page with lots of accordions open and you just want to go up or find a previous section. Alternatively, you can have a go to the top of page button, but I really feel strongly about having them as sub lists.

**Comment by donjo** [comment]
Closing this out for now since it's uncertain which page/site this is about. Re-open if more information is provided.
