### ISSUE TITLE
Update footer with new layout

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards-docs#112]
See mock-up here: https://gsa.invisionapp.com/share/FBAA2B78N#/screens/217421484

**Comment by yowill** [comment]
[Possible footer language](https://docs.google.com/document/d/1dXxn031FVd2DFaEfHTrVF9m2yAyaOcHbbFbcnRgNbro/edit):

Become a part of the community
The U.S. Web Design Standards has grown into a blossoming community of government engineers, content specialists, and designers supporting each other. With more than 100+ sites using the WDS, 3,000+ Github project followers, and 500+ forks, there’s a large and active community supporting, and actively using this open source project. 
We’re from the government, and we’re here to help.

**Comment by kategarklavs** [comment]
I love it! (Especially _We're from the government and we're here to help_)

Also, hello, WDS team!

**Comment by juliaelman** [comment]
Pull request submitted! 🚀
