### ISSUE TITLE
[Repo, Build] Remove `assets/`, have it created at start of build

### ISSUE THREAD

**Issue by yozlet** [18F/web-design-standards-docs#16]
Part of overall `assets` cleanup. (#8)

  - [x] Build step creates `assets/` at the start
  - [x] `git rm assets/` and add to `.gitignore`
  - [ ] Ensure that `vendor` subfolders (inside `img`, `css` and `js`) are all being created properly

**Comment by juliaelman** [comment]
@yozlet looks like the last part for this is placing the `uswds` into a vendor folder. Happy to tackle that if you'd like! 😄
