### ISSUE TITLE
a:focus state in sticky nav causes nav height to change (Chrome bug)

### ISSUE THREAD

**Issue by sawyerh** [18F/web-design-standards-docs#181]
There's currently a [Chrome bug related to `position: sticky`](https://bugs.chromium.org/p/chromium/issues/detail?id=695729&q=box-shadow) where a `box-shadow` on a decendent causes the sticky element to become offset. Here's a demo of what this currently looks like in the context of the docs site:

![bug](https://cloud.githubusercontent.com/assets/371943/23333234/1b2099aa-fb56-11e6-88c7-7cd754d75a32.gif)

Though this is a Chrome bug, I wanted to bring it to your attention since some may get the wrong impression that the bug lives within the WDS link component and therefore not trust it.

**Comment by juliaelman** [comment]
@sawyerh thank you for opening this issue and your support of the Standards. We are working on a solve now and appreciate you making us aware of this bug.

**Comment by juliaelman** [comment]
Fixed and launched to production. Thanks for your help! 🎉
