### ISSUE TITLE
Instructions for where things live "HTML" on developers page

### ISSUE THREAD

**Issue by mjankowski** [18F/web-design-standards-docs#192]
This page - https://standards.usa.gov/getting-started/developers/ - claims that HTML markup for components live in `docs/_components`.

I suspect this is something which changed historically, and it's not clear to me w/out doing a deep dive on the history as to whether this should be:

- The `_components` directory in the `web-design-standards-docs` repo, or;
- The `src/html` directory in the `web-design-standards` repo

The evolution of those two locations and their relationship to each other is also unclear.

I will turn this into a PR to clarify the instruction on that line if someone can confirm what it's intended to indicate (ie, are we pointing people to a location that lives within the WDS repo itself meant to show off some HTML components ... or are we trying to point people to the place where the docs site itself is grabbing the samples used in the site from).

My guess is that this points to a thing which used to exist and was subsequently migrated to the docs repo?

**Comment by juliaelman** [comment]
@mjankowski thank you for opening this issue to get clarification on where the HTML for the components resides in our documentation. You are correct that it should be pointing to `src/html`.

As for historical context, the website code base originally lived in the same repository as the main Standards library. We received feedback from users that this was confusing to have both the site and the library living in the same code base. We also wanted to have a way to deploy the site without having to put out a release of the Standards themselves. The `docs` folder is where the site lived and `_components` is where the HTML base was for each component lived as well.

I hope this helps clear up any confusion and we look forward to reviewing your pull requests!
