### ISSUE TITLE
Could you make it clearer that this is not some sort of official regulation?

### ISSUE THREAD

**Issue by togakangaroo** [18F/web-design-standards-docs#197]
I appreciate what yall are trying to do but I have a concern about some of the implicit messaging of using the `standards.usa.gov` domain and how it might be perceived.

Specifically I am wary of situations where a (non-government) client would demand to know why I chose - let's say - LESS over SASS when the latter is "official standard". Or come to me in a panic because they are afraid that some tech choice for their website places them out of compliance with the US government.

I think that avoiding this misunderstanding would only be a minor adjustment: Just some verbiage on the main page that this is for internal government services but yall consider it to be a good starting point for anyone would suffice. I realize that the Getting Started page says

> The U.S. Web Design Standards provide design guidelines and code to help you quickly create trustworthy, accessible, and consistent digital government services.

But something on the main paged and phrased a bit easier to understand for the layman would be preferable.

Thank you

**Comment by juliaelman** [comment]
@togakangaroo thank you for opening this issue. We're looking at updating our homepage soon and are going to take your concerns into consideration when developing that. We'll also be taking a look at the footer copy to help address this issue.

Leaving this issue open until that update to the homepage and footer have been made.

**Comment by togakangaroo** [comment]
Credit to yall for taking the issue seriously and responding rapidly. You're doing a great job!

**Comment by juliaelman** [comment]
Adding comment here from https://github.com/18F/web-design-standards/issues/1755 for us to consider:

> @juliaelman Again, I haven't looked at the code yet, but as a hypothetical example, would a page footer design be required? The Social Security Administration has its own, as do most other agencies, and I'd like to know whether this would be an issue. I think the other posting you referenced is roughly the same concern, so thanks for including that. This really boils down to what would be considered mandatory and whether it poses any conflicts.

**Comment by yowill** [comment]
Here's a draft of updated language to the footer (along with the updated header text in Brad's mock) to help clarify the standards are not a requirement: 

**Become a part of the community**

The U.S. Web Design Standards has grown into a blossoming community of government engineers, content specialists, and designers. This open source project is not a Federal requirement for agencies, but it is a great starting point. We currently support dozens of agencies and more than 100 sites, which is fueled through an active community of contributors both in and out of government. This project is maintained by 18F, an office within GSA.

We’re from the government, and we’re here to help.

**Comment by bradnunnally** [comment]
This has been added as part of the work for #198
