### ISSUE TITLE
Scrolling while having navigation open doesn't allow you to see the bottom of the navigation

### ISSUE THREAD

**Issue by lucasmbrown-usds** [18F/web-design-standards-docs#204]
## Description

I'd expect that I could scroll to see the bottom of the navigation menu on the left-hand side of the screen.

## Steps to reproduce the issue

1. Expand one of the left-hand menu items (E.g., form templates)
2. Scroll downward

## Additional information

![scrolling](https://cloud.githubusercontent.com/assets/25443529/23719054/c8da230e-0407-11e7-9677-8a522e053a41.gif)

**Comment by juliaelman** [comment]
Added to our next sprint - thank you for opening this issue @lucasmbrown-usds!

**Comment by juliaelman** [comment]
Fixed in #208 -  thanks for opening this issue @lucasmbrown-usds!
