### ISSUE TITLE
Design page for "Websites and apps" using the Standards

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards-docs#211]
There is currently a list of websites using the Standards located in the main repo. This issue is for designing a page on the docs site that preserves this file, as well as gives a space on the site to display this work.

We did something similar for the [Getting started](https://github.com/18F/web-design-standards-docs/pull/129) page where we dynamically pull in the `CONTRIBUTING.md` file.

**Comment by bradnunnally** [comment]
Initial take at a portfolio site. Need to review with the team and then make edits. There is also a link to a page which would be a clean display of the markdown file that currently exists. 

https://gsa.invisionapp.com/share/35BB46989#/228975811_Gettings_Started_-_Portfolio

**Comment by bradnunnally** [comment]
Final draft is posted after review and collaboration with the team - https://gsa.invisionapp.com/share/35BB46989#/228975811_Gettings_Started_-_Portfolio

Next steps is to identify the specific sites we want to showcase and to write the content for each. I'll be making those issues here shortly.
