### ISSUE TITLE
Typo in design principles

### ISSUE THREAD

**Issue by wonjunetai** [18F/web-design-standards-docs#213]
## Description

There's a typo in https://standards.usa.gov/design-principles/:

Under the `Design for flexibility.` heading, the last sentence currently says: 

> The USWDS wants to empower teams across to government to make the statement “good enough for government work” **means** something again.

Recommending change to:

> The USWDS wants to empower teams across to government to make the statement “good enough for government work” **mean** something again.

Thank you 👍

**Comment by juliaelman** [comment]
@wonjunetai thank you for opening this issue! I have added to our next sprint for review and to implement into our workflow.
