### ISSUE TITLE
Add alert to WDS site to inform users of repo split

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards-docs#24]
## Description

As part of the larger repo-split comms plan, I'd like to add an alert to standards.usa.gov to let users know about the repo split. Here's the proposed copy:

`The Standards' GitHub repos have changed! [web-design-standards](https://github.com/18F/web-design-standards) is the code base for the Standards themselves, and [web-design-standards-docs](https://github.com/18F/web-design-standards-docs) contains the code and documentation for this site.`

My thought is that this alert could stay up for several weeks (perhaps up to a month?), just to give folks enough time to get used to the change. 

As far as placement of the alert goes, this is something I need your helps with! I'm thinking it might be good above all of the other page content — what say you, visually inclined folks?

cc @maya @juliaelman @lauraGgit @donjo @jameshupp

**Comment by maya** [comment]
Maybe we can link `web-design-standards` and `web-design-standards-docs` to their repos too.

Also, I think you meant to tag @lauraponce :)

**Comment by kategarklavs** [comment]
@maya Indeed! (I saw Laura G commenting in the wds channel & then accidentally added her!). @lauraponce — apologies for the missing tag 😌

**Comment by kategarklavs** [comment]
@maya — yep! +1 to linking :)

**Comment by jameshupp** [comment]
If we're using one of our alerts, we'll need separate copy for the header and the body. So something like ...

    ### Changes to the Github repos for the Standards
    
    There are now separate repos for the Standards and for the documentation of 
    the Standards. [web-design-standards](https://github.com/18F/web-design-standards) is 
    the code base for the Standards themselves, and [web-design-standards-docs]
    (https://github.com/18F/web-design-standards-docs) contains the code and 
    documentation for this site.

**Comment by kategarklavs** [comment]
Excellent call, @jameshupp! And +1 to the header copy -- my only recommendation would be to capitalize the "H" in GitHub. 

@maya — is there anything else that you all need, content-wise? Or is this good to go?

**Comment by maya** [comment]
@kategarklavs content looks good! 

The next thing we need is guidance on placement from @donjo or @bradnunnally.

**Comment by kategarklavs** [comment]
@maya Exxxxcellent! I'm glad to hear it 😌

**Comment by donjo** [comment]
I mocked this up quick in chrome dev tools. Is this roughly what we were thinking, placement-wise?  Should it show up in every category? or just on the overview? 

Also, do we have any existing guidance on how to dismiss notifications like this? I can come up with something but wasn't sure if there is a precedent. 

![screen shot 2016-09-09 at 2 33 53 pm](https://cloud.githubusercontent.com/assets/776987/18400254/9ea388b4-769a-11e6-9b02-d2d4b3a9ded5.png)

(also, excuse the fact that I just pasted the markdown in there directly)

**Comment by jameshupp** [comment]
I can see why someone would want to dismiss it, but since we're thinking it's a short-term thing (roughly a month) maybe it's not that big a deal? If you have time, go for it, but I wouldn't worry too much for this instance.

As to where it shows up: I'm thinking this components overview page, and `getting-started\developers`. Is that too hairy to make happen?

Reasoning: individual component pages don't really rely on someone understanding how our code and assets are set up; they'll have to go to Github or to `getting-started` to figure out more. I don't think the split really affects designers who are downloading the assets, so we could hold it down one more level at `getting-started\developers`. Basically then: the homepage plus the one internal page where it directly affects the user.

@kategarklavs @maya Does that all sound right to you?

**Comment by donjo** [comment]
That makes sense to me. I haven't looked at the page template structure just yet but I can't imagine it will be a problem.

**Comment by kategarklavs** [comment]
@donjo This looks great, and I agree with @jameshupp's points. Re: dismissing it, I also think that, because this will be a temporary alert, not including a means to dismiss is probably just fine. Placement looks good, too. And finally, +1 to James' reasoning behind including the alert on the components overview + dev Getting Started pages only.

**Comment by juliaelman** [comment]
This is completed and now appears on staging - see screenshots below.

![screen shot 2016-09-13 at 9 45 08 am](https://cloud.githubusercontent.com/assets/955558/18476113/cfb70c56-7996-11e6-963d-363c0abf8a71.png)
