### ISSUE TITLE
Update WDS site footer text

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards-docs#25]
## Description

Currently, WDS footer copy includes this:

`Feedback? Edit this page or create an issue on the GitHub repository. You can also email us at uswebdesignstandards@gsa.gov.`

Being that we have multiple repos, my thought is that we should update the copy accordingly:

`Feedback? Create an issue in our [Standards component repo](https://github.com/18F/web-design-standards) or email us at uswebdesignstandards@gsa.gov.`

cc @jameshupp @juliaelman @maya & co! 

Note: Here's a screenshot of the current copy (for reference):

<img width="672" alt="screen shot 2016-09-02 at 10 51 18 am" src="https://cloud.githubusercontent.com/assets/10051548/18327560/fa9adeca-74ff-11e6-94a1-13070adbb7ed.png">

**Comment by juliaelman** [comment]
@kategarklavs 👍  looks good!

Maybe we could also add a link on each page stating `Edit this page` with a link to the markdown file for editing the page the user is on. That way if folks have feedback for the website and docs they have an easy way to do so. 

Check out how we do this on [18F page](https://pages.18f.gov/), scroll to the bottom.

**Comment by kategarklavs** [comment]
@juliaelman I like it! Going to update the copy now to add an "Edit this page" link.

**Comment by juliaelman** [comment]
Closing this, as it was completed in #62
