### ISSUE TITLE
Draft comms strategy for releases/larger comms plan

### ISSUE THREAD

**Issue by AndreaSigz** [18F/web-design-standards-docs#271]
For each of the releases (1.1, 1.2, etc), it would be good to have a template/checklist to make sure ppl are aware of the updates each time.

For smaller releases, will need 1-2 sentences summarizing the update and next steps. Larger releases may need a few paragraphs to explain the updates.

Possible outreach points:
1. Blog/summary paragraph for site
2. Blog for 18f blog & DigitalGov (with Comms slow turnaround, maybe only do for larger releases)
2. Public slack channel
3. Internal slack channels for TTS - News, i-would-tweet-for-you
4. Mailing list (not sure who is on that)
5. DigitalGov Community of Practice Managers listserv to send to related/interested communities: open-source, web managers, mobile, social media, UX

Any other missing outlets?

**Comment by bradnunnally** [comment]
This looks like a great list for outreach channels.

**Comment by AndreaSigz** [comment]
And here's a larger Draft Comms Plan. Have it in Gdocs now since it's large, but can add here if it's easier for ppl to view. Please edit/update it!
https://docs.google.com/document/d/1impxAFfaa1W22LJQZ1mc-ZohXrJjbL5hsOfqkYBNd6Y/edit#
Thanks!

**Comment by AndreaSigz** [comment]
Closing this and moving info to original issue: Press Issues 1829
