### ISSUE TITLE
Accordion toggle behavior broken on form templates page

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards-docs#278]
from Slack:

> The accordion toggle behavior appears to be broken on the doc pages at standards.usa.gov (https://standards.usa.gov/components/form-templates/ is what I'm currently on). Double-checked that I have JS enabled. Safari 10.1 + OS X 10.12.4

**Comment by donjo** [comment]
possibly related to 18f/web-design-standards#1225

**Comment by teebolt** [comment]
Have noticed this as well. Chrome 58 (Latest) on macOS (Latest). 

No errors in the console, content is loaded into the DOM, but accordions fail to expand. 
Example - https://standards.usa.gov/components/typography
