### ISSUE TITLE
https://standards.usa.gov/page-templates/ code accordions don't work

### ISSUE THREAD

**Issue by wslack** [18F/web-design-standards-docs#283]
On page load, the accordion loads as closed and can't be opened.

<img width="1123" alt="screen shot 2017-05-02 at 5 41 24 pm" src="https://cloud.githubusercontent.com/assets/10016577/25640703/96af1af6-2f5e-11e7-914b-02ef31fc0968.png">

**Comment by donjo** [comment]
Fixed in #285
