### ISSUE TITLE
Text for retired OmniGraffle files is unclear

### ISSUE THREAD

**Issue by stvnrlly** [18F/web-design-standards-docs#288]
There are OminiGraffle files [available for download](https://github.com/18F/web-design-standards-docs/blob/master/_includes/download-buttons-design.html#L12), though they're listed as "retired". The sentence accompanying them is: "The following design files have been retired and are available to maintained by the U.S. Web Design Standards." I tried to submit a patch to remove the typo ("are available to maintained"), but I couldn't figure out what the sentence is supposed to say.

- When were the files retired? What is the last version of the standards that used them?
- If it's relevant, why were they retired?
- Are they maintained, or just made available?

**Comment by AndreaSigz** [comment]
Hi @stvnrlly thanks for the question. @romkedehaan @donjo @shawnbot any thoughts?

**Comment by donjo** [comment]
Ahh good catch. It should probably say something like:

"The following design files have been retired as of version 1.0.0. While the files are no longer being maintained, the final versions remain available for download at the links below"

Depending on if we want to write that in plural form when there is only one file. The reason for retirement was a low usage rate FYI. Not sure if we want/need to put that in the description.

**Comment by bradnunnally** [comment]
One of the intents of the message was to give "permissions" to those that might be using the Omnigraffle template to make updates and submit those updates as contributions.

**Comment by romkedehaan** [comment]
I like @donjo's recco.

**Comment by donjo** [comment]
> The following design files are no longer being maintained by the U.S. Web Design Standards team as of version 1.0.0 — the most recent versions remain available for download at the links below. While the Standards team is no longer maintaining these files, we'd love to hear from any teams that are using these files and adding new components when new versions of the Standards are released. [Send us an email](mailto:uswebdesignstandards@gsa.gov).

@bradnunnally something like this?

**Comment by bradnunnally** [comment]
LGTM! @donjo
