### ISSUE TITLE
Create homepage designs for hero image + icons

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards-docs#304]
For wrapping up the new homepage that will launch sometime after 1.2 we need a new hero image to replace the sparkler/flag and icons to go with the 2x2 graphic list grid of features outlined in @bradnunnally's wireframe.

https://gsa.invisionapp.com/share/R4B53T5A5#/227109282_Homepage_-_Desktop

**Comment by rtwell** [comment]
new image here: [wds-homeimage.zip](https://github.com/18F/web-design-standards-docs/files/1062330/wds-homeimage.zip)

I would suggest limiting this issue to the home page header image, and making a new issue(s) to cover the rest of the changes (spacing, icons, additional graphics)

**Comment by yowill** [comment]
CLOSED!
