### ISSUE TITLE
<meta name="description"> content contains the whole page's content

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards-docs#333]
When looking at the generated source code for our HTML files, I noticed that the `<meta name="description">` tags in the header have a `content` attribute that is set to the entire content of the page (with HTML tags removed), rather than merely a snippet of it. For pages with a lot of content, this could bloat the page size, and I'm not sure how helpful it is to search engines and other tools that use that `<meta>` tag.

**Comment by maya** [comment]
Closed in #474.
