### ISSUE TITLE
update form templates style

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards-docs#370]
take a look at what's optional vs required

**Comment by rtwell** [comment]
### Name form template
- [ ] Remove the Suffix form field
- [ ] Remove all "Required" indicators, and denote form fields with "optional"
![image](https://user-images.githubusercontent.com/12564977/29521465-4d391c48-864b-11e7-8bb5-efd2c2b3c6e7.png)

**Comment by donjo** [comment]
this was addressed in 18F/web-design-standards#2081
