### ISSUE TITLE
update dropdown

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards-docs#372]
default to     - Select -  instead of the first option

show example of the dropdown in dropdown state

**Comment by rtwell** [comment]
### Closed state:
![image](https://user-images.githubusercontent.com/12564977/29521035-56b5ca66-8649-11e7-87ed-bde359b58f81.png)
a) the default text should be "Select" 
b) I changed the carat on the right to be [this SVG](https://github.com/18F/web-design-standards-docs/files/1238904/Sort.zip)
### Expanded state
![image](https://user-images.githubusercontent.com/12564977/29521207-2629b2a8-864a-11e7-9494-32a171357735.png)

**Comment by donjo** [comment]
because we are using the browser's native interface for styling the dropdown options, I'm going to suggest we only display the updated closed state and leave it as an interactive component.
