### ISSUE TITLE
Link to 18F/uswds-simple-sass?

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards-docs#380]
Last week, Eric Mill was making a simple one-page static site and needed to customize the site's SASS, but without using a big complicated static asset build pipeline or Jekyll, so I made him this minimal example project:

https://github.com/18F/uswds-simple-sass

It happens to use node JS, but that's practically just an implementation detail--what this *really* is, is a command-line "kit" for making a simple Standards-based one-pager that allows for SASS customization.

I'm wondering if it'd be useful to link to it somewhere from the docs site.  Possibly the [implementations](https://standards.usa.gov/getting-started/implementations/) page, though it's a little unusual in that it doesn't really "integrate" with a particular framework like a lot of other other projects do.

**Comment by donjo** [comment]
I guess "fixes" doesn't necessarily close the parent issue. this has been merged in so closing this
