### ISSUE TITLE
Websites sidenav menu for release notes links are dead

### ISSUE THREAD

**Issue by TommiHe** [18F/web-design-standards-docs#421]
/whats-new/releases is opening correctly, but when trying to use the links on sidenav the versions don't open the correct chapter. Http changes, but nothing happens when trying to click version links. Other sidenav links on other pages seem to work fine.

https://standards.usa.gov/whats-new/releases/
Dead links after releases

Using Google chrome 61.0.3163.100 (64bit) tried also with Edge, didnt work eather.

**Comment by thisisdano** [comment]
I see that the links are pointing to anchors of the format `version-1-4-1` but the `h2`s are id'd in the format `version-141`. Lemme see what I can do.

**Comment by maya** [comment]
Fixed in #424.
