### ISSUE TITLE
Add content questions to interview guide

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards-docs#43]
As part of our metrics-tracking strategy, @jameshupp and I would like to add some site-copy-related questions to the interview guide to get a better sense of 1) how effective the Getting Started copy is and 2) what else users might like to see.

(Note: The interview guide already has some questions about component-related documentation.)

**Comment by juliaelman** [comment]
Talked with @bradnunnally and we've got these covered - closing!
