### ISSUE TITLE
Sidenav first item should say "Overview" not the page title

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards-docs#430]
The sidenav first item should say "Overview" not the page title as defined in https://github.com/18F/web-design-standards-docs/blob/develop/_data/nav.yml#L19

@donjo do you know why this is happening?

**Comment by donjo** [comment]
@maya no but it's something I encountered when I was working on the data design standards (which I forked from this project repo) so it's definitely a bug. I'll do some digging.

**Comment by maya** [comment]
Closed via #476.
