### ISSUE TITLE
Remove 18F logo in footer?

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards-docs#432]
Since the project is no longer under run by 18F, should we remove the logo in the footer? Or replace it with something else (OPP, TTS)?

<img width="1111" alt="screen shot 2017-11-01 at 4 13 14 pm" src="https://user-images.githubusercontent.com/5249443/32302381-a1b43070-bf1f-11e7-8a7e-3aa80bae306b.png">

We still link to and advertise training offerings on the homepage, which I assume will be processed by 18F so maybe that's a reason to keep it in? 

/cc @thisisdano

**Comment by thisisdano** [comment]
I think we'll want to change the footer copy, at least, to say that the project is `maintained by the Office of Products and Platforms (OPP), an office within GSA`. Beyond that, though, we'll need to reach out to 18F to discuss just what we need to convey on this page wrt services and consulting.

**Comment by thisisdano** [comment]
I think we should also add something to the footer along the lines of `This site is hosted by Federalist.`, possibly with a federalist logo as well.

**Comment by maya** [comment]
I think the Federalist team will like that approach. FYSA @wslack

**Comment by wslack** [comment]
Not my circus/monkeys, but I like the idea of the standards being `a project of the Technology Transformation Services, maintained by the Office of Products and Platforms, and hosted on Federalist.`

**Comment by maya** [comment]
Got the OK to remove the 18F logo from @joshuabailes.

**Comment by thisisdano** [comment]
How about: `The U.S. Web Design Standards are a project of GSA's Technology Transformation Service, maintained by the Office of Products and Platforms. This website is hosted on Federalist.`

**Comment by maya** [comment]
The project is singular, should it be "the U.S. Web Design Standards is"? I know we've referred to the Standards in plural form when it's shortened, i.e. the "Standards are," just not just with the whole name.
