### ISSUE TITLE
Features section of homepage should be linked

### ISSUE THREAD

**Issue by thisisdano** [18F/web-design-standards-docs#433]
This is the what I'm calling the `Features` section:
<img width="1049" alt="screen shot 2017-11-02 at 9 48 12 am" src="https://user-images.githubusercontent.com/11464021/32338852-32473414-bfb3-11e7-9155-4a9114455d12.png">

It seems like a nice little section, but the items aren't linked to the relevant pages. If we're going to call out sections and functionality, it would be nice to link to the a place on the site to learn more. It was confusing to realize that these are not links.

### todo
- [ ] link from each individual Features highlight to its relevant section of the site.

**Comment by donjo** [comment]
Closing this since #391 exists
