### ISSUE TITLE
Diamond decoration on homepage not showing in Chrome

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards-docs#439]
The diamond decoration is not showing in Chrome, but it is showing in Safari and Firefox. Note: it's two different sizes in Safari and Firefox.

### Chrome (horizontal line / no show)
<img width="1117" alt="diamond" src="https://user-images.githubusercontent.com/5249443/32460994-547647ee-c2e9-11e7-838f-ded696fef507.png">

### Safari (smaller)
<img width="1051" alt="screen shot 2017-11-06 at 11 53 26 am" src="https://user-images.githubusercontent.com/5249443/32461041-73dd661c-c2e9-11e7-8482-1e4fc755b4af.png">

### Firefox (larger)
<img width="1053" alt="screen shot 2017-11-06 at 11 53 15 am" src="https://user-images.githubusercontent.com/5249443/32461052-78d15142-c2e9-11e7-941a-376bd84bff8b.png">

Pretty minor issue but FYSA @donjo

**Comment by thisisdano** [comment]
I'd vote for getting rid of that diamond altogether
