### ISSUE TITLE
[Website]: Issues in web-design-standards repo related to the website

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards-docs#44]
## Description

Issues in the `web-design-standards` repo related to the website (with the `[Type: Website]` label): https://github.com/18F/web-design-standards/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BType%5D+Website%22

**Comment by juliaelman** [comment]
Closing this issue, as there are no longer any issues on the main repo with that label 🎉
