### ISSUE TITLE
Adjust vertical padding in footer

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards-docs#442]
According to the latest homepage designs the footer content should have a bit more padding at the top and bottom. It's currently set to `2rem` via the `$spacing-medium` variable and should be bumped up to 4rem via a yet-to-be-added `$spacing-x-large` variable, at least in the full screen desktop view. 

see 18f/web-design-standards#2209 for more info/discussion 

![screen shot 2017-11-06 at 5 14 31 pm](https://user-images.githubusercontent.com/776987/32468941-fe899f7a-c315-11e7-8d4e-370c0e7c95a3.png)

**Comment by maya** [comment]
I'll make sure to address this in #445.
