### ISSUE TITLE
https://standards.usa.gov does not follow label standards

### ISSUE THREAD

**Issue by aretecode** [18F/web-design-standards-docs#454]
https://standards.usa.gov/components/labels/
https://github.com/18F/web-design-standards/blob/9ff31e9e2c8906246b79d233116ef842cbc5a52c/src/components/03-labels/labels.config.yml
https://github.com/18F/web-design-standards/blob/9ff31e9e2c8906246b79d233116ef842cbc5a52c/src/components/03-labels/labels.njk

<img width="1042" alt="screen shot 2017-11-19 at 4 29 51 am" src="https://user-images.githubusercontent.com/4022631/32990678-7d730d5a-cce2-11e7-83c0-82e4e8cda57b.png">

**Comment by maya** [comment]
Thanks for opening this @aretecode. Could you share more details about what you were expecting from the label?

**Comment by maya** [comment]
Closing for now, if you're able to respond with more detail, we'd be glad to re-open.
