### ISSUE TITLE
Improve hero copy on homepage

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards-docs#467]
Should we update the text to more accurately reflect the USWDS and what's come out of our vision work?

### Current text
>The Standards are a design system that allows federal agencies to quickly prototype and deploy digital products using a baseline of design patterns.

#### A few issues
>deploy digital products

We don't offer anything to deploy digital products, that's more something Federalist does. 

>allows federal agencies to quickly prototype

It's used by more than federal agencies, also contractors

### An alternate idea
The Standards provides styles and UI components to design and build accessible, responsive, and consistent digital products for the federal government.

The Standards provides a baseline of design patterns to design and build accessible, responsive, and consistent digital products for the federal government.

### Duplicate title
We have the "U.S. Web Design Standards" appearing twice in the logo and title. Another possibility: "A design system for the federal government"

**Comment by thisisdano** [comment]
Yes, I like these! How about something like:

#### A design system for the federal government
The Standards provides research-backed design patterns for building accessible, responsive, and consistent digital products for the federal government.

**Comment by maya** [comment]
Works for me 🎉  cc @donjo for visibility.
