### ISSUE TITLE
aria-labelledby is misspelled

### ISSUE THREAD

**Issue by luigi** [18F/web-design-standards-docs#480]
## Description

On this page: https://standards.usa.gov/components/form-controls/

The docs mention `aria-labeledby`. The correct spelling is `aria-labelledby`.

http://accessibleculture.org/articles/2011/03/its-spelled-aria-labelledby/

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

**Comment by maya** [comment]
Thanks @luigi! Fixing that here #481.
