### ISSUE TITLE
[Website + WDS]: Update site files and WDS to 0.12.0

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards-docs#6]
## Description

- [x] Update the site to use v0.12.0
- [x] Update the Standards site to use the latest documentation files with the v0.12.0 release
- [x] Restore build-time Prism syntax highlighting
  - [x] Remove `copy-prism-javascript` step and invocation from `config/gulp/javascript.js`

**Comment by juliaelman** [comment]
Pull request opened here: https://github.com/18F/web-design-standards-docs/pull/22

**Comment by juliaelman** [comment]
Closed via #22
